config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/subs')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:show, :new, :create]

  resources :comments, only: [:create, :show] do
     member do
      post 'downvote'
      post 'upvote'
    end
  end

  resources :subs, except: [:destroy]

  resources :posts, except: [:destroy, :index] do
    member do
      post 'downvote'
      post 'upvote'
    end
    resources :comments, only: [:new]

  end

end

app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :description, presence: true
    validates :title, uniqueness: true

    belongs_to :moderator,
        class_name: :User,
        foreign_key: :moderator_id

    has_many :post_subs, dependent: :destroy
    has_many :posts,
        through: :post_subs,
        source: :post
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController 
    
    before_action :require_user!, except: [:index, :show]
    before_action :require_user_owns_sub!, only: [:edit, :update]

    def index
        @subs = Sub.all
    end

    def show
        @sub = Sub.find(params[:id])
    end

    def new
        @sub = Sub.new
    end

    def create
        @sub = current_user.subs.new(sub_params)
        if @sub.save
            redirect_to subs_url 
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def edit
        @sub = Sub.find(params[:id])
    end

    def update
        @sub = Sub.find(params[:id])
        if @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    private

    def require_user_owns_sub!
        return if current_user.subs.find_by(id: params[:id])
        render json: 'You are not allowed to edit this sub!', status: :forbidden
    end

    def sub_params
        params.require(:sub).permit(:title, :description)
    end


end

app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>
<% http_method = sub.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
    <input type="hidden" name="_method" value="<%= http_method %>">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <label>
        Title
        <input type="text" name="sub[title]" value="<%= sub.title %>">
    </label>
    
    <br><br>

    <label>
        Description
        <textarea name="sub[description]"><%= sub.description %></textarea>
    </label>
    
    <br><br>

    <input type="submit" value="Submit">
</form>

app/views/subs/edit.html.erb
<div>
    <h1>Edit your sub</h1>

    <%= render "form", sub: @sub %>
</div>

app/views/subs/index.html.erb
<div>
<h1>All the subjects!</h1>
    <ul>
        <% @subs.each do |sub| %>
            <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
        <% end %>
    </ul>
    <a href="<%= new_sub_url %>">New Sub!</a>
</div>

app/views/subs/new.html.erb
<div>
    <h1>Create a new Sub</h1>
    <%= render "form", sub: @sub %>
</div>

app/views/subs/show.html.erb
<div>
    <h1>
        <%= @sub.title %>
    </h1>


    <h3>Description</h3>
    <h4><%= @sub.description %></h4>

    <h4>Links</h4>
    <a href="<%= edit_sub_url(@sub) if @sub.moderator == current_user %>">Edit Sub</a>
    <br>
    <a href="<%= new_post_url %>">New Post!</a>

    <h4>Posts</h4>
    <% if @sub.posts.length > 0 %>
        <ul>
            <% @sub.posts.each do |post| %>
                <li>(<%= post.user_votes %>)<a href="<%= post_url(post) %>"><%= post.title %></a></li>
            <% end %>
        </ul>
    <% else %>
        <p>This sub has no posts...yet</p>
    <% end %>
</div>