config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/subs')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:show, :new, :create]

  resources :comments, only: [:create, :show] do
     member do
      post 'downvote'
      post 'upvote'
    end
  end

  resources :subs, except: [:destroy]

  resources :posts, except: [:destroy, :index] do
    member do
      post 'downvote'
      post 'upvote'
    end
    resources :comments, only: [:new]

  end

end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :subs, presence: { message: 'must have at least one sub' }

    belongs_to :author,
        class_name: :User,
        foreign_key: :user_id

    has_many :post_subs, dependent: :destroy
    has_many :subs, 
        through: :post_subs,
        source: :sub

    has_many :comments
    
    has_many :votes, as: :votable, class_name: "Vote"

    def comments_by_parent
        comments_by_parent = Hash.new { |hash, key| hash[key] = [] }

        self.comments.includes(:author).each do |comment|
            comments_by_parent[comment.parent_comment_id] << comment
        end
        comments_by_parent
    end

    def user_votes
        self.votes.sum(:value)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_user!, except: [:show] 
    before_action :require_user_owns_post!, only: [:edit, :update]
    
    def new
        @post = Post.new
    end

    def create
        @post = current_user.posts.new(post_params)
        if @post.save
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
            if @post.update(post_params)
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :edit
        end
    end

    def downvote
        vote(-1)
    end

    def upvote
        vote(1)
    end

    private
    def post_params
        params.require(:post).permit(:url, :title, :content, :user_id, sub_ids: [])
    end

    def require_user_owns_post!
        return if current_user.posts.find_by(id: params[:id])
        render json: 'Forbidden', status: :forbidden
    end

    def vote(direction)
        @post = Post.find(params[:id])
        @vote = @post.votes.find_or_initialize_by(user: current_user)

        unless @vite.update(value: direction)
            flash[:errors] = @vote.errors.full_messages
        end
        redirect_to post_url(@post)
    end
end

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% http_method = post.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>
    Title:
    <input name="post[title]" value="<%= post.title %>">
  </label>
  <br>

  <label>
    URL:
    <input name="post[url]" value="<%= post.url %>">
  </label>
  <br>

  <label>
    Content:
    <textarea name="post[content]"><%= post.content %></textarea>
  </label>
  <br>

  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
    <label>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked" if post.sub_ids.include?(sub.id) %>>
      <%= sub.title %>
    </label>
    <br>
  <% end %>

  <input type="Submit" value="Submit">
</form>

app/views/posts/edit.html.erb
<div>
  <h1>Edit Post!</h1>
  <%= render "form", post: @post %>
</div>

app/views/posts/new.html.erb
<div>
  <h1>New Post!</h1>
  <%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<h4>
(<%= @post.user_votes %>)
Post title:
    <a href="<%= post_url(@post) %>"><%= @post.title %></a>
    <br>
    Author: <%= @post.author.email %>
</h4>
<div>
    <b>Content:</b>
    <pre><%= @post.content %></pre>
</div>

<a href="<%= edit_post_url(@post) if @post.author == current_user %>">Edit</a>

<form action="<%= upvote_post_url(@post) %>" method="post">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <input type="submit" value="Upvote">
</form>
<form action="<%= downvote_post_url(@post) %>" method="post">
    <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
    <input type="submit" value="Downvote">
</form>

<h2>Subs</h2>
<ul>
    <% @post.subs.each do |sub| %>
        <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
    <% end %>
</ul>

<h2>Comments</h2>
<a href="<%= new_post_comment_url(@post.id) %>">Comment on this post!</a>

<ul>
    <% comments_by_parent = @post.comments_by_parent %>
    <% comments_by_parent[nil].each do |top_level_comment| %>
      <li>
        <%= render("comments/comment",
                   comment: top_level_comment,
                   comments_by_parent: comments_by_parent) %>
      </li>
    <% end %>
</ul>