config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/subs')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:show, :new, :create]

  resources :comments, only: [:create, :show] do
     member do
      post 'downvote'
      post 'upvote'
    end
  end

  resources :subs, except: [:destroy]

  resources :posts, except: [:destroy, :index] do
    member do
      post 'downvote'
      post 'upvote'
    end
    resources :comments, only: [:new]

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
   <% if logged_in? %>
      <nav>
        <a class='button' href="<%= subs_url %>">Take me Home</a>
        <div class='user-detail'>
          <p>Logged in as: <%= current_user.email %></p>
        <form action=<%= session_url %> method='post'>
          <input
            type="hidden"
            name="_method"
            value="delete">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
          <input 
            type="submit" value="Log Out">
        </form>
        </div>
      </nav>
  <% else %>
      <nav>
        <a href="<%= new_user_url %>">Sign Up</a>
        <a href="<%= new_session_url %>">Log In</a>
      </nav>
  <% end %>
      
  <% if flash[:errors] %>
    <p><%= flash[:errors].join(", ") %></p>
  <% end %>

    <%= yield %>
  </body>
</html>